language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js: '8'
install: yarn install
jobs:
  include:
    - script: yarn test
    - script: npx codecov@3
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
